export type ScreenshotCaptureOwner = "marketing" | "checklists" | "auth" | "product";
export type ScreenshotCaptureSurface = "public" | "auth" | "product";
export type ScreenshotCaptureAuthMode = "none" | "real";
export type ScreenshotCaptureDynamicSource = "company" | "document" | "gakuchika";

export type ScreenshotCaptureRoute = {
  id: `${ScreenshotCaptureOwner}.${string}`;
  pathTemplate: `/${string}`;
  page: `src/app/${string}/page.tsx`;
  owner: ScreenshotCaptureOwner;
  surface: ScreenshotCaptureSurface;
  authMode: ScreenshotCaptureAuthMode;
  outputGroup: ScreenshotCaptureOwner;
  dynamicParams?: Readonly<Record<string, ScreenshotCaptureDynamicSource>>;
  expectedFinalPath?: `/${string}`;
};

export const screenshotCaptureRoutes = [
  {
    id: "marketing.home",
    pathTemplate: "/",
    page: "src/app/(marketing)/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.aiMensetsu",
    pathTemplate: "/ai-mensetsu",
    page: "src/app/(marketing)/ai-mensetsu/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.contact",
    pathTemplate: "/contact",
    page: "src/app/(marketing)/contact/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.dataSourcePolicy",
    pathTemplate: "/data-source-policy",
    page: "src/app/(marketing)/data-source-policy/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.entrySheetAi",
    pathTemplate: "/entry-sheet-ai",
    page: "src/app/(marketing)/entry-sheet-ai/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.esAiGuide",
    pathTemplate: "/es-ai-guide",
    page: "src/app/(marketing)/es-ai-guide/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.esTensakuAi",
    pathTemplate: "/es-tensaku-ai",
    page: "src/app/(marketing)/es-tensaku-ai/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.gakuchikaAi",
    pathTemplate: "/gakuchika-ai",
    page: "src/app/(marketing)/gakuchika-ai/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.legal",
    pathTemplate: "/legal",
    page: "src/app/(marketing)/legal/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.pricing",
    pathTemplate: "/pricing",
    page: "src/app/(marketing)/pricing/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.pricingCheckout",
    pathTemplate: "/pricing/checkout",
    page: "src/app/(marketing)/pricing/checkout/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.privacy",
    pathTemplate: "/privacy",
    page: "src/app/(marketing)/privacy/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.shiboudoukiAi",
    pathTemplate: "/shiboudouki-ai",
    page: "src/app/(marketing)/shiboudouki-ai/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.shukatsuAi",
    pathTemplate: "/shukatsu-ai",
    page: "src/app/(marketing)/shukatsu-ai/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.shukatsuKanri",
    pathTemplate: "/shukatsu-kanri",
    page: "src/app/(marketing)/shukatsu-kanri/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.templates",
    pathTemplate: "/templates",
    page: "src/app/(marketing)/templates/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.templatesGakuchikaStar",
    pathTemplate: "/templates/gakuchika-star",
    page: "src/app/(marketing)/templates/gakuchika-star/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.templatesShiboudouki",
    pathTemplate: "/templates/shiboudouki",
    page: "src/app/(marketing)/templates/shiboudouki/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.terms",
    pathTemplate: "/terms",
    page: "src/app/(marketing)/terms/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.tools",
    pathTemplate: "/tools",
    page: "src/app/(marketing)/tools/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.toolsEsCounter",
    pathTemplate: "/tools/es-counter",
    page: "src/app/(marketing)/tools/es-counter/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
  },
  {
    id: "marketing.waitlist",
    pathTemplate: "/waitlist",
    page: "src/app/(marketing)/waitlist/page.tsx",
    owner: "marketing",
    surface: "public",
    authMode: "none",
    outputGroup: "marketing",
    expectedFinalPath: "/login",
  },
  {
    id: "checklists.index",
    pathTemplate: "/checklists",
    page: "src/app/checklists/page.tsx",
    owner: "checklists",
    surface: "public",
    authMode: "none",
    outputGroup: "checklists",
  },
  {
    id: "checklists.deadlineManagement",
    pathTemplate: "/checklists/deadline-management",
    page: "src/app/checklists/deadline-management/page.tsx",
    owner: "checklists",
    surface: "public",
    authMode: "none",
    outputGroup: "checklists",
  },
  {
    id: "auth.login",
    pathTemplate: "/login",
    page: "src/app/(auth)/login/page.tsx",
    owner: "auth",
    surface: "auth",
    authMode: "none",
    outputGroup: "auth",
  },
  {
    id: "auth.onboarding",
    pathTemplate: "/onboarding",
    page: "src/app/(auth)/onboarding/page.tsx",
    owner: "auth",
    surface: "auth",
    authMode: "real",
    outputGroup: "auth",
  },
  {
    id: "product.dashboard",
    pathTemplate: "/dashboard",
    page: "src/app/(product)/dashboard/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.companies",
    pathTemplate: "/companies",
    page: "src/app/(product)/companies/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.companyNew",
    pathTemplate: "/companies/new",
    page: "src/app/(product)/companies/new/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.companyDetail",
    pathTemplate: "/companies/[id]",
    page: "src/app/(product)/companies/[id]/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
    dynamicParams: { id: "company" },
  },
  {
    id: "product.companyMotivation",
    pathTemplate: "/companies/[id]/motivation",
    page: "src/app/(product)/companies/[id]/motivation/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
    dynamicParams: { id: "company" },
  },
  {
    id: "product.companyInterview",
    pathTemplate: "/companies/[id]/interview",
    page: "src/app/(product)/companies/[id]/interview/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
    dynamicParams: { id: "company" },
  },
  {
    id: "product.deadlines",
    pathTemplate: "/deadlines",
    page: "src/app/(product)/deadlines/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.es",
    pathTemplate: "/es",
    page: "src/app/(product)/es/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.esDetail",
    pathTemplate: "/es/[id]",
    page: "src/app/(product)/es/[id]/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
    dynamicParams: { id: "document" },
  },
  {
    id: "product.gakuchika",
    pathTemplate: "/gakuchika",
    page: "src/app/(product)/gakuchika/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.gakuchikaDetail",
    pathTemplate: "/gakuchika/[id]",
    page: "src/app/(product)/gakuchika/[id]/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
    dynamicParams: { id: "gakuchika" },
  },
  {
    id: "product.tasks",
    pathTemplate: "/tasks",
    page: "src/app/(product)/tasks/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.calendar",
    pathTemplate: "/calendar",
    page: "src/app/(product)/calendar/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.calendarConnect",
    pathTemplate: "/calendar/connect",
    page: "src/app/(product)/calendar/connect/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.calendarSettings",
    pathTemplate: "/calendar/settings",
    page: "src/app/(product)/calendar/settings/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.interviewDashboard",
    pathTemplate: "/interview/dashboard",
    page: "src/app/(product)/interview/dashboard/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.notifications",
    pathTemplate: "/notifications",
    page: "src/app/(product)/notifications/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.profile",
    pathTemplate: "/profile",
    page: "src/app/(product)/profile/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.search",
    pathTemplate: "/search",
    page: "src/app/(product)/search/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
  {
    id: "product.settings",
    pathTemplate: "/settings",
    page: "src/app/(product)/settings/page.tsx",
    owner: "product",
    surface: "product",
    authMode: "real",
    outputGroup: "product",
  },
] as const satisfies readonly ScreenshotCaptureRoute[];

export type ScreenshotCaptureRouteDefinition = (typeof screenshotCaptureRoutes)[number];
export type ScreenshotCaptureRouteId = ScreenshotCaptureRouteDefinition["id"];
export type ScreenshotCapturePathTemplate = ScreenshotCaptureRouteDefinition["pathTemplate"];

export function getScreenshotCaptureRouteById(
  id: string,
): ScreenshotCaptureRouteDefinition | undefined {
  return screenshotCaptureRoutes.find((route) => route.id === id);
}
