import { describe, expect, it } from "vitest";
import type { Task } from "@/hooks/useTasks";
import {
  buildGroupedTasks,
  getDaysLeft,
  getDueLabel,
  getTaskGroup,
  matchesTaskQuery,
  sortTasks,
} from "./task-display";

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: "task-1",
    userId: "user-1",
    guestId: null,
    companyId: null,
    applicationId: null,
    deadlineId: null,
    title: "ES作成",
    description: null,
    type: "es",
    status: "open",
    dueDate: "2026-05-21T00:00:00.000Z",
    isAutoGenerated: false,
    sortOrder: 0,
    completedAt: null,
    createdAt: "2026-05-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
    company: null,
    application: null,
    deadline: null,
    ...overrides,
  };
}

describe("task-display", () => {
  const baseDate = new Date("2026-05-21T09:00:00.000Z");

  it("classifies tasks by due date and status", () => {
    expect(getTaskGroup(makeTask({ dueDate: "2026-05-20T00:00:00.000Z" }), baseDate)).toBe("overdue");
    expect(getTaskGroup(makeTask({ dueDate: "2026-05-21T00:00:00.000Z" }), baseDate)).toBe("today");
    expect(getTaskGroup(makeTask({ dueDate: "2026-05-22T00:00:00.000Z" }), baseDate)).toBe("upcoming");
    expect(getTaskGroup(makeTask({ dueDate: null }), baseDate)).toBe("noDue");
    expect(getTaskGroup(makeTask({ status: "done" }), baseDate)).toBe("done");
  });

  it("treats invalid due dates as no due date", () => {
    const task = makeTask({ dueDate: "not-a-date" });

    expect(getDaysLeft(task.dueDate, baseDate)).toBeNull();
    expect(getTaskGroup(task, baseDate)).toBe("noDue");
    expect(getDueLabel(task, baseDate)).toBe("期限なし");
  });

  it("builds grouped tasks without dropping empty groups", () => {
    const grouped = buildGroupedTasks(
      [
        makeTask({ id: "overdue", dueDate: "2026-05-20T00:00:00.000Z" }),
        makeTask({ id: "done", status: "done" }),
      ],
      baseDate,
    );

    expect(grouped.overdue).toHaveLength(1);
    expect(grouped.today).toHaveLength(0);
    expect(grouped.upcoming).toHaveLength(0);
    expect(grouped.noDue).toHaveLength(0);
    expect(grouped.done).toHaveLength(1);
  });

  it("sorts open tasks by due date before completed tasks", () => {
    const done = makeTask({ id: "done", status: "done", dueDate: "2026-05-19T00:00:00.000Z" });
    const later = makeTask({ id: "later", dueDate: "2026-05-23T00:00:00.000Z" });
    const earlier = makeTask({ id: "earlier", dueDate: "2026-05-22T00:00:00.000Z" });

    expect([done, later, earlier].sort((a, b) => sortTasks(a, b, "priority")).map((task) => task.id)).toEqual([
      "earlier",
      "later",
      "done",
    ]);
  });

  it("matches title, description, company, and deadline text", () => {
    const task = makeTask({
      title: "提出物準備",
      description: "証明写真を添付する",
      company: { id: "company-1", name: "東京海上日動火災保険" },
      deadline: { id: "deadline-1", title: "ES締切", dueDate: "2026-05-30T00:00:00.000Z" },
    });

    expect(matchesTaskQuery(task, "証明写真")).toBe(true);
    expect(matchesTaskQuery(task, "東京海上")).toBe(true);
    expect(matchesTaskQuery(task, "ES締切")).toBe(true);
    expect(matchesTaskQuery(task, "面接")).toBe(false);
  });
});
