/**
 * Template-based task generation for deadlines.
 *
 * Maps deadline types to template categories, fetches templates from DB,
 * resolves dependency chains, and batch-inserts tasks in a transaction.
 */

import { db } from "@/lib/db";
import { tasks, taskTemplates } from "@/lib/db/schema";
import { eq } from "drizzle-orm";

/** Maps deadline type → template category. null = no templates available. */
const DEADLINE_TYPE_TO_TEMPLATE_CATEGORY: Record<string, string | null> = {
  es_submission: "es_submission",
  web_test: "test",
  aptitude_test: "test",
  interview_1: "interview",
  interview_2: "interview",
  interview_3: "interview",
  interview_final: "interview",
  briefing: "briefing",
  internship: "internship",
  offer_response: "offer_response",
  other: null,
};

export { DEADLINE_TYPE_TO_TEMPLATE_CATEGORY };

interface GenerateTasksParams {
  deadlineId: string;
  deadlineType: string;
  deadlineDueDate: Date;
  companyId: string;
  applicationId: string | null;
  userId: string | null;
  guestId: string | null;
}

/**
 * Generate tasks for a deadline based on its type's template category.
 * Uses db.transaction() to ensure atomic insert (no partial task creation).
 * Returns the IDs of the created tasks.
 */
export async function generateTasksForDeadline(params: GenerateTasksParams): Promise<string[]> {
  const category = DEADLINE_TYPE_TO_TEMPLATE_CATEGORY[params.deadlineType];
  if (!category) return [];

  const templates = await db
    .select()
    .from(taskTemplates)
    .where(eq(taskTemplates.category, category))
    .orderBy(taskTemplates.sortOrder);

  if (templates.length === 0) return [];

  const now = new Date();

  // Pre-generate UUIDs so we can resolve dependency references
  const taskIds = templates.map(() => crypto.randomUUID());

  // Build sortOrder → taskId map for dependency resolution
  const sortOrderToTaskId = new Map<number, string>();
  templates.forEach((t, i) => {
    sortOrderToTaskId.set(t.sortOrder, taskIds[i]);
  });

  const taskValues = templates.map((template, i) => {
    // Calculate due date: deadline.dueDate - daysBeforeDeadline, clamped to [now, deadline.dueDate]
    const rawDueDate = new Date(
      params.deadlineDueDate.getTime() - template.daysBeforeDeadline * 24 * 60 * 60 * 1000,
    );
    const clampedDueDate = new Date(
      Math.min(
        params.deadlineDueDate.getTime(),
        Math.max(now.getTime(), rawDueDate.getTime()),
      ),
    );

    // Resolve dependency
    const dependsOnTaskId =
      template.dependsOnSortOrder != null
        ? sortOrderToTaskId.get(template.dependsOnSortOrder) ?? null
        : null;

    return {
      id: taskIds[i],
      userId: params.userId,
      guestId: params.guestId,
      companyId: params.companyId,
      applicationId: params.applicationId,
      deadlineId: params.deadlineId,
      title: template.title,
      type: template.taskType as typeof tasks.$inferInsert.type,
      status: "open" as const,
      dueDate: clampedDueDate,
      isAutoGenerated: true,
      sortOrder: template.sortOrder,
      dependsOnTaskId,
      isBlocked: dependsOnTaskId != null,
      templateKey: `${category}.${template.title}`,
      createdAt: now,
      updatedAt: now,
    };
  });

  return db.transaction(async (tx) => {
    await tx.insert(tasks).values(taskValues);
    return taskIds;
  });
}
