/**
 * Tasks Hook
 *
 * Manages tasks for the user
 */

import { useState, useEffect, useCallback } from "react";
import { useAuth } from "@/components/auth/AuthProvider";
import { parseApiErrorResponse, toAppUiError } from "@/lib/api-errors";
import {
  notifyError,
  notifyTaskCreated,
  notifyTaskDeleted,
  notifyTaskSaved,
  notifyTaskStatusChanged,
} from "@/lib/notifications";

export type TaskType =
  | "es"
  | "web_test"
  | "self_analysis"
  | "gakuchika"
  | "video"
  | "other";

export type TaskStatus = "open" | "done";

export const TASK_TYPE_LABELS: Record<TaskType, string> = {
  es: "ES作成",
  web_test: "WEBテスト",
  self_analysis: "自己分析",
  gakuchika: "ガクチカ",
  video: "動画・録画",
  other: "その他",
};

export interface Task {
  id: string;
  userId: string | null;
  guestId: string | null;
  companyId: string | null;
  applicationId: string | null;
  deadlineId: string | null;
  title: string;
  description: string | null;
  type: TaskType;
  status: TaskStatus;
  dueDate: string | null;
  isAutoGenerated: boolean;
  sortOrder: number;
  completedAt: string | null;
  createdAt: string;
  updatedAt: string;
  company?: {
    id: string;
    name: string;
  } | null;
  application?: {
    id: string;
    name: string;
  } | null;
  deadline?: {
    id: string;
    title: string;
    dueDate: string;
  } | null;
}

export interface TodayTask {
  mode: "DEADLINE" | "DEEP_DIVE" | null;
  task: Task | null;
  message?: string;
}

interface UseTodayTaskOptions {
  initialData?: TodayTask;
}

export interface CreateTaskInput {
  title: string;
  description?: string;
  type: TaskType;
  companyId?: string;
  applicationId?: string;
  deadlineId?: string;
  dueDate?: string;
}

export interface UpdateTaskInput {
  title?: string;
  description?: string;
  type?: TaskType;
  status?: TaskStatus;
  dueDate?: string | null;
}

function buildHeaders(): Record<string, string> {
  return {
    "Content-Type": "application/json",
  };
}

export interface UseTasksOptions {
  status?: TaskStatus | "all";
  companyId?: string;
  applicationId?: string;
  initialData?: Task[];
}

interface UpdateTaskNotifyOptions {
  success: "saved" | "toggle";
  toggledTo?: TaskStatus;
}

export function useTasks(options: UseTasksOptions = {}) {
  const [tasks, setTasks] = useState<Task[]>(() => options.initialData ?? []);
  const [isLoading, setIsLoading] = useState(() => !options.initialData);
  const [error, setError] = useState<string | null>(null);

  const fetchTasks = useCallback(async () => {
    setIsLoading(true);
    setError(null);

    try {
      const params = new URLSearchParams();
      if (options.status) params.set("status", options.status);
      if (options.companyId) params.set("companyId", options.companyId);
      if (options.applicationId) params.set("applicationId", options.applicationId);

      const url = `/api/tasks${params.toString() ? `?${params.toString()}` : ""}`;
      const response = await fetch(url, {
        headers: buildHeaders(),
        credentials: "include",
      });

      if (!response.ok) {
        throw await parseApiErrorResponse(
          response,
          {
            code: "TASKS_FETCH_FAILED",
            userMessage: "タスク一覧を読み込めませんでした。",
            action: "ページを再読み込みして、もう一度お試しください。",
            retryable: true,
          },
          "useTasks.fetch"
        );
      }

      const data = await response.json();
      setTasks(data.tasks || []);
    } catch (err) {
      const uiError = toAppUiError(
        err,
        {
          code: "TASKS_FETCH_FAILED",
          userMessage: "タスク一覧を読み込めませんでした。",
          action: "ページを再読み込みして、もう一度お試しください。",
          retryable: true,
        },
        "useTasks.fetch"
      );
      setError(uiError.message);
    } finally {
      setIsLoading(false);
    }
  }, [options.status, options.companyId, options.applicationId]);

  useEffect(() => {
    if (options.initialData) {
      return;
    }
    fetchTasks();
  }, [fetchTasks, options.initialData]);

  const createTask = useCallback(
    async (input: CreateTaskInput): Promise<Task | null> => {
      try {
        const response = await fetch("/api/tasks", {
          method: "POST",
          headers: buildHeaders(),
          credentials: "include",
          body: JSON.stringify(input),
        });

        if (!response.ok) {
          throw await parseApiErrorResponse(
            response,
            {
              code: "TASK_CREATE_FAILED",
              userMessage: "タスクを作成できませんでした。",
              action: "入力内容を確認して、もう一度お試しください。",
              retryable: response.status >= 500,
            },
            "useTasks.create"
          );
        }

        const data = await response.json();
        const nextTask: Task = {
          ...data.task,
          company: null,
          application: null,
          deadline: null,
        };
        setTasks((prev) => (options.status === "done" ? prev : [nextTask, ...prev]));
        notifyTaskCreated();
        return nextTask;
      } catch (err) {
        const uiError = toAppUiError(
          err,
          {
            code: "TASK_CREATE_FAILED",
            userMessage: "タスクを作成できませんでした。",
            action: "入力内容を確認して、もう一度お試しください。",
            retryable: true,
          },
          "useTasks.create"
        );
        setError(uiError.message);
        notifyError({
          title: uiError.message,
          description: uiError.action ?? undefined,
        });
        return null;
      }
    },
    [options.status]
  );

  const updateTaskInternal = useCallback(
    async (
      taskId: string,
      input: UpdateTaskInput,
      notifyOptions: UpdateTaskNotifyOptions
    ): Promise<boolean> => {
      try {
        const response = await fetch(`/api/tasks/${taskId}`, {
          method: "PUT",
          headers: buildHeaders(),
          credentials: "include",
          body: JSON.stringify(input),
        });

        if (!response.ok) {
          throw await parseApiErrorResponse(
            response,
            {
              code: "TASK_UPDATE_FAILED",
              userMessage: "タスクを更新できませんでした。",
              action: "入力内容を確認して、もう一度お試しください。",
              retryable: response.status >= 500,
            },
            "useTasks.update"
          );
        }

        const data = await response.json();
        setTasks((prev) => {
          const nextTasks = prev.map((task) =>
            task.id === taskId
              ? {
                  ...task,
                  ...data.task,
                  dueDate: data.task.dueDate ?? task.dueDate,
                  completedAt: data.task.completedAt ?? null,
                }
              : task
          );

          if (options.status === "open") {
            return nextTasks.filter((task) => task.status === "open");
          }
          if (options.status === "done") {
            return nextTasks.filter((task) => task.status === "done");
          }

          return nextTasks;
        });
        if (notifyOptions.success === "toggle") {
          notifyTaskStatusChanged(notifyOptions.toggledTo === "done");
        } else {
          notifyTaskSaved();
        }
        return true;
      } catch (err) {
        const uiError = toAppUiError(
          err,
          {
            code: "TASK_UPDATE_FAILED",
            userMessage: "タスクを更新できませんでした。",
            action: "入力内容を確認して、もう一度お試しください。",
            retryable: true,
          },
          "useTasks.update"
        );
        setError(uiError.message);
        notifyError({
          title: uiError.message,
          description: uiError.action ?? undefined,
        });
        return false;
      }
    },
    [options.status]
  );

  const updateTask = useCallback(
    async (taskId: string, input: UpdateTaskInput): Promise<boolean> =>
      updateTaskInternal(taskId, input, { success: "saved" }),
    [updateTaskInternal]
  );

  const deleteTask = useCallback(
    async (taskId: string): Promise<boolean> => {
      try {
        const response = await fetch(`/api/tasks/${taskId}`, {
          method: "DELETE",
          headers: buildHeaders(),
          credentials: "include",
        });

        if (!response.ok) {
          throw await parseApiErrorResponse(
            response,
            {
              code: "TASK_DELETE_FAILED",
              userMessage: "タスクを削除できませんでした。",
              action: "時間を置いて、もう一度お試しください。",
              retryable: response.status >= 500,
            },
            "useTasks.delete"
          );
        }

        setTasks((prev) => prev.filter((task) => task.id !== taskId));
        notifyTaskDeleted();
        return true;
      } catch (err) {
        const uiError = toAppUiError(
          err,
          {
            code: "TASK_DELETE_FAILED",
            userMessage: "タスクを削除できませんでした。",
            action: "時間を置いて、もう一度お試しください。",
            retryable: true,
          },
          "useTasks.delete"
        );
        setError(uiError.message);
        notifyError({
          title: uiError.message,
          description: uiError.action ?? undefined,
        });
        return false;
      }
    },
    []
  );

  const toggleComplete = useCallback(
    async (taskId: string): Promise<boolean> => {
      const task = tasks.find((t) => t.id === taskId);
      if (!task) return false;

      const newStatus = task.status === "open" ? "done" : "open";
      return updateTaskInternal(taskId, { status: newStatus }, { success: "toggle", toggledTo: newStatus });
    },
    [tasks, updateTaskInternal]
  );

  return {
    tasks,
    isLoading,
    error,
    refresh: fetchTasks,
    createTask,
    updateTask,
    deleteTask,
    toggleComplete,
  };
}

export function useTodayTask(options: UseTodayTaskOptions = {}) {
  const { isLoading: isAuthLoading } = useAuth();
  const [data, setData] = useState<TodayTask>(() => options.initialData ?? { mode: null, task: null });
  const [isLoading, setIsLoading] = useState(() => !options.initialData);
  const [error, setError] = useState<string | null>(null);

  const fetchTodayTask = useCallback(async () => {
    if (isAuthLoading) {
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch("/api/tasks/today", {
        headers: buildHeaders(),
        credentials: "include",
      });

      if (!response.ok) {
        if (response.status === 401) {
          setData({ mode: null, task: null });
          return;
        }

        throw await parseApiErrorResponse(
          response,
          {
            code: "TODAY_TASK_FETCH_FAILED",
            userMessage: "今日のおすすめタスクを読み込めませんでした。",
            action: "ページを再読み込みして、もう一度お試しください。",
            retryable: true,
          },
          "useTodayTask.fetch"
        );
      }

      const result = await response.json();
      setData(result);
    } catch (err) {
      const uiError = toAppUiError(
        err,
        {
          code: "TODAY_TASK_FETCH_FAILED",
          userMessage: "今日のおすすめタスクを読み込めませんでした。",
          action: "ページを再読み込みして、もう一度お試しください。",
          retryable: true,
        },
        "useTodayTask.fetch"
      );
      setError(uiError.message);
    } finally {
      setIsLoading(false);
    }
  }, [isAuthLoading]);

  useEffect(() => {
    if (options.initialData) {
      return;
    }
    if (isAuthLoading) {
      return;
    }
    fetchTodayTask();
  }, [fetchTodayTask, isAuthLoading, options.initialData]);

  const markComplete = useCallback(async (): Promise<boolean> => {
    if (!data.task) return false;

    try {
      const response = await fetch(`/api/tasks/${data.task.id}`, {
        method: "PUT",
        headers: buildHeaders(),
        credentials: "include",
        body: JSON.stringify({ status: "done" }),
      });

      if (!response.ok) {
        throw await parseApiErrorResponse(
          response,
          {
            code: "TASK_COMPLETE_FAILED",
            userMessage: "タスクを完了にできませんでした。",
            action: "時間を置いて、もう一度お試しください。",
            retryable: response.status >= 500,
          },
          "useTodayTask.markComplete"
        );
      }

      setData({ mode: null, task: null });
      notifyTaskStatusChanged(true);
      return true;
    } catch (err) {
      const uiError = toAppUiError(
        err,
        {
          code: "TASK_COMPLETE_FAILED",
          userMessage: "タスクを完了にできませんでした。",
          action: "時間を置いて、もう一度お試しください。",
          retryable: true,
        },
        "useTodayTask.markComplete"
      );
      setError(uiError.message);
      notifyError({
        title: uiError.message,
        description: uiError.action ?? undefined,
      });
      return false;
    }
  }, [data.task]);

  return {
    ...data,
    isLoading: isAuthLoading || isLoading,
    error,
    refresh: fetchTodayTask,
    markComplete,
  };
}
