import type { CompanyStatus } from "@/lib/constants/status";
import type { CompanyLogoCandidate } from "@/lib/company-logo-types";

export type DashboardNearestDeadline = {
  id: string;
  title: string;
  dueDate: string;
  type: string;
  daysLeft: number;
};

export type DashboardCompany = {
  id: string;
  userId: string | null;
  guestId: string | null;
  name: string;
  industry: string | null;
  recruitmentUrl: string | null;
  corporateUrl: string | null;
  mypageUrl: string | null;
  hasCredentials: boolean;
  notes: string | null;
  status: CompanyStatus;
  isPinned: boolean;
  sortOrder: number;
  infoFetchedAt: string | null;
  corporateInfoFetchedAt: string | null;
  createdAt: string;
  updatedAt: string;
  estimatedLogoCandidates?: CompanyLogoCandidate[];
  estimatedLogoDomains?: string[];
  estimatedFaviconUrl?: string | null;
  nearestDeadline: DashboardNearestDeadline | null;
  applicationCount: number;
  activeApplicationCount: number;
  documentCount: number;
  esDocumentCount: number;
};

export type CompaniesPageData = {
  companies: DashboardCompany[];
  count: number;
  limit: number | null;
  canAddMore: boolean;
};

export type DashboardDeadline = {
  id: string;
  companyId: string;
  company: string;
  type: string;
  title: string;
  description: string | null;
  dueDate: string;
  daysLeft: number;
  isConfirmed: boolean;
  confidence: "high" | "medium" | "low" | null;
  sourceUrl: string | null;
};

export type DeadlinesPageData = {
  deadlines: DashboardDeadline[];
  count: number;
  periodDays: number;
};

export type DashboardTaskType =
  | "es"
  | "web_test"
  | "self_analysis"
  | "gakuchika"
  | "video"
  | "other";

export type DashboardTaskStatus = "open" | "done";

export type DashboardTask = {
  id: string;
  userId: string | null;
  guestId: string | null;
  companyId: string | null;
  applicationId: string | null;
  deadlineId: string | null;
  title: string;
  description: string | null;
  type: DashboardTaskType;
  status: DashboardTaskStatus;
  dueDate: string | null;
  isAutoGenerated: boolean;
  sortOrder: number;
  completedAt: string | null;
  createdAt: string;
  updatedAt: string;
  company?: {
    id: string;
    name: string;
  } | null;
  application?: {
    id: string;
    name: string;
  } | null;
  deadline?: {
    id: string;
    title: string;
    dueDate: string;
  } | null;
};

export type TodayTaskData = {
  mode: "DEADLINE" | "DEEP_DIVE" | null;
  task: DashboardTask | null;
  message?: string;
};

export type TasksPageData = {
  tasks: DashboardTask[];
};
