import { renderToStaticMarkup } from "react-dom/server";
import { createElement } from "react";
import { describe, it, expect, vi } from "vitest";
import { TodayTasksCard } from "./TodayTasksCard";
import type { Task, TodayTask } from "@/hooks/useTasks";

function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: "task-1",
    userId: "user-1",
    guestId: null,
    companyId: null,
    applicationId: null,
    deadlineId: null,
    title: "期限なしタスク",
    description: null,
    type: "other",
    status: "open",
    dueDate: null,
    isAutoGenerated: false,
    sortOrder: 0,
    completedAt: null,
    createdAt: "2026-05-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
    company: null,
    application: null,
    deadline: null,
    ...overrides,
  };
}

function makeTodayTask(task: Task | null = null): TodayTask & {
  isLoading: boolean;
  markComplete: () => Promise<boolean>;
} {
  return {
    mode: task ? "DEADLINE" : null,
    task,
    isLoading: false,
    markComplete: vi.fn(async () => true),
  };
}

describe("TodayTasksCard", () => {
  it("exports TodayTasksCard component", async () => {
    const mod = await import("./TodayTasksCard");
    expect(mod.TodayTasksCard).toBeDefined();
  });

  it("uses compact padding and section separators", async () => {
    const { readFile } = await import("node:fs/promises");
    const source = await readFile(new URL("./TodayTasksCard.tsx", import.meta.url), "utf8");
    expect(source).toContain("p-2");
    expect(source).toContain("my-1");
    expect(source).not.toMatch(/\bmy-3\b/);
  });

  it("supports dashboard-controlled open task density via maxOpenTasks", async () => {
    const { readFile } = await import("node:fs/promises");
    const source = await readFile(new URL("./TodayTasksCard.tsx", import.meta.url), "utf8");
    expect(source).toContain("maxOpenTasks");
  });

  it("does not use taskTypeBarColors (vertical color bars removed)", async () => {
    const { readFile } = await import("node:fs/promises");
    const source = await readFile(new URL("./TodayTasksCard.tsx", import.meta.url), "utf8");
    expect(source).not.toContain("taskTypeBarColors");
  });

  it("uses JST-based daysLeft calculation", async () => {
    const { readFile } = await import("node:fs/promises");
    const source = await readFile(new URL("./TodayTasksCard.tsx", import.meta.url), "utf8");
    expect(source).toContain("getJSTDaysLeft");
    expect(source).toContain("Asia/Tokyo");
  });

  it("has urgency-based section grouping", async () => {
    const { readFile } = await import("node:fs/promises");
    const source = await readFile(new URL("./TodayTasksCard.tsx", import.meta.url), "utf8");
    expect(source).toContain("最優先");
    expect(source).toContain("今日中");
    expect(source).toContain("今週");
    expect(source).toContain("その他");
  });

  it("keeps deadlines in the standalone DeadlineCard", async () => {
    const { readFile } = await import("node:fs/promises");
    const source = await readFile(new URL("./TodayTasksCard.tsx", import.meta.url), "utf8");
    expect(source).not.toContain("deadlines?: Deadline[]");
    expect(source).not.toContain("confirmedDeadlines");
  });

  it("does not wrap entire task rows in Link (no nested interactive elements)", async () => {
    const { readFile } = await import("node:fs/promises");
    const source = await readFile(new URL("./TodayTasksCard.tsx", import.meta.url), "utf8");
    // The ItemRow wrapper should be a div, not a Link
    expect(source).toContain('<div className="group flex items-center gap-3 rounded-lg p-2');
  });

  it("uses dashboard assets and a real task toggle callback", async () => {
    const { readFile } = await import("node:fs/promises");
    const source = await readFile(new URL("./TodayTasksCard.tsx", import.meta.url), "utf8");
    expect(source).toContain("next/image");
    expect(source).toContain("/dashboard/assets/image_09.png");
    expect(source).toContain("onToggleTask");
    expect(source).toContain("onCompleteTodayTask");
    expect(source).not.toContain("Visual-only");
  });

  it("renders open tasks without due dates instead of empty state", () => {
    const html = renderToStaticMarkup(
      createElement(TodayTasksCard, {
        todayTask: makeTodayTask(),
        openTasks: [makeTask()],
      })
    );

    expect(html).toContain("期限なしタスク");
    expect(html).toContain("その他");
    expect(html).not.toContain("未完了のタスクはありません");
  });

  it("does not render inert overflow menu buttons", () => {
    const html = renderToStaticMarkup(
      createElement(TodayTasksCard, {
        todayTask: makeTodayTask(makeTask({ id: "today-task", title: "最優先タスク" })),
        openTasks: [makeTask({ id: "task-2", title: "通常タスク" })],
      })
    );

    expect(html).not.toContain("その他のアクション");
  });
});
